"""sprint0_add_smtp_imap_warmup_to_inbox_connections

Revision ID: 36ba9f7b3384
Revises: f9e76c743931
Create Date: 2026-03-27 15:29:21.955893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36ba9f7b3384'
down_revision: Union[str, Sequence[str], None] = 'f9e76c743931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox_connections', sa.Column('smtp_host', sa.String(), nullable=True))
    op.add_column('inbox_connections', sa.Column('imap_host', sa.String(), nullable=True))
    op.add_column('inbox_connections', sa.Column('is_warmup_enabled', sa.Boolean(), nullable=True))
    op.add_column('inbox_connections', sa.Column('daily_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inbox_connections', 'daily_limit')
    op.drop_column('inbox_connections', 'is_warmup_enabled')
    op.drop_column('inbox_connections', 'imap_host')
    op.drop_column('inbox_connections', 'smtp_host')
    # ### end Alembic commands ###
