"""add smtp to domains

Revision ID: 899f4502eada
Revises: 9f3d8ff1cb8d
Create Date: 2026-05-25 13:17:51.917410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '899f4502eada'
down_revision: Union[str, Sequence[str], None] = '9f3d8ff1cb8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('smtp_host', sa.String(), nullable=True))
    op.add_column('domains', sa.Column('smtp_port', sa.Integer(), nullable=True))
    op.add_column('domains', sa.Column('smtp_username', sa.String(), nullable=True))
    op.add_column('domains', sa.Column('smtp_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domains', 'smtp_password')
    op.drop_column('domains', 'smtp_username')
    op.drop_column('domains', 'smtp_port')
    op.drop_column('domains', 'smtp_host')
    # ### end Alembic commands ###
