"""update alert rules columns

Revision ID: 9f3d8ff1cb8d
Revises: b004474cbde2
Create Date: 2026-05-06 16:29:28.408223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f3d8ff1cb8d'
down_revision: Union[str, Sequence[str], None] = 'b004474cbde2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_rules', sa.Column('condition', sa.String(), nullable=False))
    op.add_column('alert_rules', sa.Column('threshold', sa.Integer(), nullable=False))
    op.add_column('alert_rules', sa.Column('target', sa.String(), nullable=False))
    op.add_column('alert_rules', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('alert_rules', 'slack_webhook_url')
    op.drop_column('alert_rules', 'trigger')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_rules', sa.Column('trigger', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('alert_rules', sa.Column('slack_webhook_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('alert_rules', 'is_active')
    op.drop_column('alert_rules', 'target')
    op.drop_column('alert_rules', 'threshold')
    op.drop_column('alert_rules', 'condition')
    # ### end Alembic commands ###
